### ISSUE TITLE
Music app breaks when previously indexed music files are removed

### ISSUE THREAD

**Issue by ignatenkobrain** [owncloud/music#373]
```
ownCloud[3213]: {index} Exception: {"Message":"","Code":0,"Trace":"#0 \/var\/lib\/owncloud\/apps\/music\/controller\/apicontroller.php(107): OCA\\Music\\Db\\Track->toCollection(Object(OC\\URLGenerator), Object(OC\\Files\\Node\\Folder))\n#1 [internal function]: OCA\\Music\\Controller\\ApiController->collection()\n#2 \/usr\/share\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#3 \/usr\/share\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#4 \/usr\/share\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'collection')\n#5 \/usr\/share\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('ApiController', 'collection', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#6 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#7 \/usr\/share\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#8 \/usr\/share\/owncloud\/lib\/base.php(771): OC\\Route\\Router->match('\/apps\/music\/api...')\n#9 \/usr\/share\/owncloud\/index.php(36): OC::handleRequest()\n#10 {main}","File":"\/var\/lib\/owncloud\/apps\/music\/db\/track.php","Line":97}
```

I've shared folder from another user, then I deleted this folder using my user and created new folder with the same name. Uploaded music and music app won't work anymore.

**Comment by jancborchardt** [comment]
Same issue here. Only the loading spinner is shown. Looks like it’s because the app expects a music file which was deleted meanwhile:
```
{"reqId":"hZY\/N0dtDEjF5Gc4Nxys","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/jan\\\/files\\\/MUCKE\\\/And So I Watch You From Afar\\\/Heirs (pre-order)\\\/And So I Watch You From Afar - Heirs - 01 Run Home.mp3\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php(178): OC\\\\Files\\\\Node\\\\Root->get('\\\/jan\\\/files\\\/MUCK...')\\n#1 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php(341): OC\\\\Files\\\\Node\\\\Folder->get('\\\/MUCKE\\\/And So I...')\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/music\\\/db\\\/track.php(95): OC\\\\Files\\\\Node\\\\Folder->getById(1614)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/music\\\/controller\\\/apicontroller.php(107): OCA\\\\Music\\\\Db\\\\Track->toCollection(Object(OC\\\\URLGenerator), Object(OC\\\\Files\\\\Node\\\\Folder))\\n#4 [internal function]: OCA\\\\Music\\\\Controller\\\\ApiController->collection()\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Music\\\\Controller\\\\ApiController), 'collection')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(104): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Music\\\\Controller\\\\ApiController), 'collection')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ApiController', 'collection', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(272): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(860): OC\\\\Route\\\\Router->match('\\\/apps\\\/music\\\/api...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php\",\"Line\":184}","level":4,"time":"2015-05-04T17:59:26+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/music\/api\/collection"}
```
Obviously it should not fail and just rescan & update.

@MorrisJobke

**Comment by miccaco** [comment]
https://github.com/owncloud/music/wiki/Debugging-and-resetting-the-database

**Comment by mitar** [comment]
Shouldn't this be automatically handled and metadata updated/removed?

**Comment by jancborchardt** [comment]
@MorrisJobke please

**Comment by depeje** [comment]
This seems to be fixed for me by just setting the music folder in the personal settings.

**Comment by paulijar** [comment]
The root cause for this bug is the fact that the Music app does not detect unshare which is initated by the user the file/folder was shared with ("unshareFromSelf"). Only unshare initiated by the file owner is detected. Hence, after using unshareFromSelf, the music database contains references to files which are no longer accessible.

After PR #564, the behavior has changes so that having references to non-existing files no longer prevents loading the music collection. The only problem is that obsolete files are shown to the user. The user cannot play these files and there is no way to get rid of them apart from rebuilding the database (with the command line utility or by changing the music path from the user settings).

**Comment by paulijar** [comment]
I created a new issue #567 describing the remaining bug. The original problem of Music app breaking totally is no longer valid and this issue can be closed.
