### ISSUE TITLE
Music scanning issues

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/music#450]
After the manual scanning process, the app stays in loading state. This is the error message I get in the log. (The referenced song does exist.)
```
{"reqId":"473zX5N6UBohjWRqRFkU","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/jan\\\/files\\\/MUCKE\\\/Reso\\\/Reso - Tangram Outtakes _ B-sides\\\/01 Aegis.mp3\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php(117): OC\\\\Files\\\\Node\\\\Root->get('\\\/jan\\\/files\\\/MUCK...')\\n#1 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/folder.php(283): OC\\\\Files\\\\Node\\\\Folder->get('\\\/MUCKE\\\/Reso\\\/Res...')\\n#2 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/music\\\/db\\\/track.php(95): OC\\\\Files\\\\Node\\\\Folder->getById(1423)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/music\\\/controller\\\/apicontroller.php(120): OCA\\\\Music\\\\Db\\\\Track->toCollection(Object(OC\\\\URLGenerator), Object(OC\\\\Files\\\\Node\\\\Folder))\\n#4 [internal function]: OCA\\\\Music\\\\Controller\\\\ApiController->collection()\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Music\\\\Controller\\\\ApiController), 'collection')\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Music\\\\Controller\\\\ApiController), 'collection')\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ApiController', 'collection', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(858): OC\\\\Route\\\\Router->match('\\\/apps\\\/music\\\/api...')\\n#12 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php\",\"Line\":181}","level":3,"time":"2015-12-01T15:36:18+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/music\/api\/collection"}
```

Then after moving that song away and even after doing a rescan:
```
{"reqId":"9YLG+kMwsnqdn77xg6YZ","remoteAddr":"127.0.0.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/jan\\\/owncloud\\\/apps\\\/music\\\/controller\\\/apicontroller.php(120): OCA\\\\Music\\\\Db\\\\Track->toCollection(Object(OC\\\\URLGenerator), Object(OC\\\\Files\\\\Node\\\\Folder))\\n#1 [internal function]: OCA\\\\Music\\\\Controller\\\\ApiController->collection()\\n#2 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Music\\\\Controller\\\\ApiController), 'collection')\\n#4 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Music\\\\Controller\\\\ApiController), 'collection')\\n#5 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ApiController', 'collection', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#8 \\\/home\\\/jan\\\/owncloud\\\/lib\\\/base.php(858): OC\\\\Route\\\\Router->match('\\\/apps\\\/music\\\/api...')\\n#9 \\\/home\\\/jan\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/jan\\\/owncloud\\\/apps\\\/music\\\/db\\\/track.php\",\"Line\":97}","level":3,"time":"2015-12-01T15:46:35+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/music\/api\/collection"}
{"reqId":"GvN044uXb7XkilC0suny","remoteAddr":"127.0.0.1","app":"music","message":"JS: Processed more files than available 1169\/1168","level":0,"time":"2015-12-01T15:46:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/music\/api\/log"}
```

@MorrisJobke @vgezer

**Comment by aauzi** [comment]
I had the same issue and turned around the problem doing the attached patch.
It may be better to handle the exception in the caller though.

[music-0.3.8-1.patch.zip](https://github.com/owncloud/music/files/74318/music-0.3.8-1.patch.zip)

**Comment by jancborchardt** [comment]
@aauzi can you open a pull request to the Music app directly here on Github to fix the issue? :)

**Comment by aauzi** [comment]
it's been fixed 13 days ago in master by commit:8af1c1b56ca4e546f4b030127dc998fb9a3e3a6e
ok, my bad! next time I'll check here first ;)

**Comment by jancborchardt** [comment]
So this can be closed @ndurchx @MorrisJobke?

**Comment by ndurchx** [comment]
@jancborchardt This problem shouldn't appear any more. So yes, this ticket can be closed.

**Comment by derkostka** [comment]
Hi i get this exception when doing a manual scan in occ. I suspect it has to do with a not readable hidden File (.AppleDouble Folder).
