### ISSUE TITLE
Can't play music, error 401

### ISSUE THREAD

**Issue by tflidd** [owncloud/music#474]
### Reproduce:
1. get latest music app (faf31d033929ae2397298c61f68476434c589020)
2. activate music app
3. upload a few mp3-files
4. play a file

### Expected result
Music is played.

### Real result
owncloud.log:
````
{"reqId":"mrAAeaPnCOhTKoRndree","remoteAddr":"my-ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/auth.php(124): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(166): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#5 \\\/var\\\/www\\\/oc9\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/oc9\\\/remote.php(138): require_once('\\\/var\\\/www\\\/oc9\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/oc9\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/auth.php\",\"Line\":148,\"User\":\"admin\"}","level":0,"time":"2016-03-08T21:19:23+00:00","method":"HEAD","url":"\/oc9\/remote.php\/webdav\/download\/emil.mp3"}
````

System: Debian 8/Apache/mod_php/ OC 9.0.0

**Comment by MorrisJobke** [comment]
@tflidd Did this work after a reload of the page?

**Comment by MorrisJobke** [comment]
> @tflidd Did this work after a reload of the page?

Nevermind - I got it too.

**Comment by MorrisJobke** [comment]
Better formatted error message:

```
{"reqId":"J35nRVw08VfDhbjFp2RU","remoteAddr":"::1","app":"webdav","message":"Exception: {\"Message\":\"HTTP/1.1 401 CSRF check not passed.\",\"Exception\":\"Sabre\DAV\Exception\NotAuthenticated\",\"Code\":0,\"Trace\":\"
#0 apps/dav/lib/connector/sabre/auth.php(124): OCA\DAV\Connector\Sabre\Auth->auth(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#1 3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php(166): OCA\DAV\Connector\Sabre\Auth->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#2 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#4 3rdparty/sabre/dav/lib/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)
#5 3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 apps/dav/appinfo/v1/webdav.php(55): Sabre\DAV\Server->exec()
#7 remote.php(138): require_once('/Users/morrisjo...')
#8 {main}\",\"File\":\"apps/dav/lib/connector/sabre/auth.php\",\"Line\":148,\"User\":\"mjob\"}","level":0,"time":"2016-03-09T08:18:44+00:00","method":"HEAD","url":"\/master\/remote.php\/webdav\/01%20-%20Adyta%20(The%20Neverending%20Embrace).mp3"}
```

**Comment by MorrisJobke** [comment]
```
::1 - - [09/Mar/2016:09:18:44 +0100] "HEAD /master/remote.php/webdav/01%20-%20Adyta%20(The%20Neverending%20Embrace).mp3 HTTP/1.1" 401 -
```

**Comment by MorrisJobke** [comment]
@LukasReschke I tried to add `'?requesttoken=' + OC.requesttoken` to the URL, but it still responds with a 401:

```
::1 - - [09/Mar/2016:09:27:54 +0100] "HEAD /master/remote.php/webdav/01%20-%20Adyta%20(The%20Neverending%20Embrace).mp3?requesttoken=ZCRLRwcsdxEFOhMzPiw+fD8nBDISJGIHHQoQFBo+IyA=:OWsvlu0PPq8BOGhDgv7tpwIeD3wN+GtQOfQJ0zHrq3w= HTTP/1.1" 401 -
```

```patch
diff --git a/js/public/musicFilePlayer.js b/js/public/musicFilePlayer.js
index a8b2166..72bef85 100644
--- a/js/public/musicFilePlayer.js
+++ b/js/public/musicFilePlayer.js
@@ -69,7 +69,7 @@ $(document).ready(function () {
 
                        soundManager.createSound({
                            id: 'ownCloudSound',
-                           url: fileURL,
+                           url: fileURL + '?requesttoken=' + OC.requestToken,
                            onstop: function() {
                                var filerow = $('#fileList').find('tr[data-file="' + filename + '"]');
                                filerow.data('playstate', null);
```

**Comment by LukasReschke** [comment]
Please try https://github.com/owncloud/music/pull/475
