### ISSUE TITLE
Symfony\Component\Routing\Exception\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\

### ISSUE THREAD

**Issue by blizzz** [owncloud/music#481]
I see this log message appearing regurlarly. The trace is:

```
 Exception: {"Exception":"Symfony\Component\Routing\Exception\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"music.page.index\" as such route does not exist.","Code":0,"Trace":"#0 /path/to/owncloud/lib/private/route/router.php(313): Symfony\Component\Routing\Generator\UrlGenerator->generate('music.page.inde...', Array, 1)
#1 /path/to/owncloud/lib/private/urlgenerator.php(66): OC\Route\Router->generate('music.page.inde...', Array)
#2 /path/to/apps-extra/music/appinfo/app.php(26): OC\URLGenerator->linkToRoute('music.page.inde...')
#3 /path/to/owncloud/lib/private/app.php(163): require_once('/var/www/minion...')
#4 /path/to/owncloud/lib/private/app.php(144): OC_App::requireAppFile('music')
#5 /path/to/owncloud/lib/private/app.php(117): OC_App::loadApp('music')
#6 /path/to/owncloud/lib/private/util.php(137): OC_App::loadApps(Array)
#7 /path/to/owncloud/lib/private/files/filesystem.php(242): OC_Util::setupFS(NULL)
#8 /path/to/owncloud/lib/private/server.php(166): OC\Files\Filesystem::getMountManager(NULL)
#9 /path/to/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#10 /path/to/owncloud/lib/private/appframework/utility/simplecontainer.php(102): Pimple\Container->offsetGet('RootFolder')
#11 /path/to/owncloud/lib/private/servercontainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('RootFolder')
#12 /path/to/owncloud/lib/private/server.php(719): OC\ServerContainer->query('RootFolder')
#13 /path/to/owncloud/lib/private/server.php(736): OC\Server->getRootFolder()
#14 /path/to/owncloud/apps/mail/appinfo/application.php(42): OC\Server->getUserFolder('$USER')
#15 /path/to/owncloud/apps/mail/appinfo/routes.php(23): OCA\Mail\AppInfo\Application->__construct()
#16 /path/to/owncloud/lib/private/route/router.php(327): include_once('/var/www/minion...')
#17 /path/to/owncloud/lib/private/route/router.php(142): OC\Route\Router->requireRouteFile('/var/www/minion...', 'mail')
#18 /path/to/owncloud/lib/private/route/router.php(307): OC\Route\Router->loadRoutes()
#19 /path/to/owncloud/lib/private/urlgenerator.php(66): OC\Route\Router->generate('mail.page.index', Array)
#20 /path/to/owncloud/apps/mail/appinfo/app.php(40): OC\URLGenerator->linkToRoute('mail.page.index')
#21 /path/to/owncloud/lib/private/app.php(163): require_once('/var/www/minion...')
#22 /path/to/owncloud/lib/private/app.php(144): OC_App::requireAppFile('mail')
#23 /path/to/owncloud/lib/private/app.php(117): OC_App::loadApp('mail')
#24 /path/to/owncloud/ocs/v1.php(47): OC_App::loadApps()
#25 /path/to/owncloud/ocs/v2.php(22): require_once('/var/www/minion...')
#26 {main}","File":"/path/to/owncloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":130} 
```

I am using music 0.3.10 against OC 9.0. 

In case it mattes, I use to have non-shipped apps in an extra folder outside of the original ownCloud folder, for reasons symlinked from within the ownCloud folder.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/owncloud/music/pull/482
