### ISSUE TITLE
Scan stops at "Scanning ... 4672/32279 "

### ISSUE THREAD

**Issue by Huster-at-github** [owncloud/music#500]
Error comes at every user, here "octest":

`Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_music_artists`(`name`,`user_id`) VALUES(?,?)' with params [\"\\xff\\xfe\", \"octest\"]:\n\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\xFF\\xFE' for column 'name' at row 1","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(174): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/statementwrapper.php(75): Doctrine\\DBAL\\Statement->execute()\n#3 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(251): OC_DB_StatementWrapper->execute()\n#4 \/var\/www\/owncloud\/lib\/public\/appframework\/db\/mapper.php(125): OCP\\AppFramework\\Db\\Mapper->execute('INSERT INTO `*P...', Array)\n#5 \/var\/www\/owncloud\/apps\/music\/businesslayer\/artistbusinesslayer.php(58): OCP\\AppFramework\\Db\\Mapper->insert(Object(OCA\\Music\\Db\\Artist))\n#6 \/var\/www\/owncloud\/apps\/music\/utility\/scanner.php(264): OCA\\Music\\BusinessLayer\\ArtistBusinessLayer->addArtistIfNotExist('\\xFF\\xFE', 'octest')\n#7 \/var\/www\/owncloud\/apps\/music\/utility\/scanner.php(399): OCA\\Music\\Utility\\Scanner->update(Object(OC\\Files\\Node\\File), 'octest')\n#8 \/var\/www\/owncloud\/apps\/music\/controller\/apicontroller.php(303): OCA\\Music\\Utility\\Scanner->rescan('octest')\n#9 [internal function]: OCA\\Music\\Controller\\ApiController->scan()\n#10 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#11 \/var\/www\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Music\\Controller\\ApiController), 'scan')\n#12 \/var\/www\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Music\\Controller\\ApiController), 'scan')\n#13 \/var\/www\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('ApiController', 'scan', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/owncloud\/lib\/private\/route\/router.php(276): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#16 \/var\/www\/owncloud\/lib\/base.php(882): OC\\Route\\Router->match('\/apps\/music\/api...')\n#17 \/var\/www\/owncloud\/index.php(39): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}`

**Comment by Huster-at-github** [comment]
Error appears when klicking on "Unscanned files available. Click here to start the scan."

**Comment by Huster-at-github** [comment]
WTF .... now I wrote a detailed test procedure, how I resolved this problem and at the end my Firefox crashed (because of the brutal Music-App-Script) and all notes are lost!    :-1: 

In short sentences: Many thanks to the **--debug** option!!!    :+1: 

Used this commands to find out what is the corrupt data of user octest:

Rescan files:
`sudo -u www-data ./occ files:scan octest`

Delete music database:
`sudo -u www-data ./occ music:reset-database octest`

Rescan music database:
`sudo -u www-data ./occ music:scan octest --debug`

FYI: My Musc app has to handle 38.000 mp3 files!
