### ISSUE TITLE
Music app not working. sudo -u www-data php occ music:scan --all output included:

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/music#559]
$ sudo -u www-data php occ music:scan --all

```
...some files are scanned, then:
Scanning /user.../files//Gemeinsame Dateien X und Y/Klingeltöne/Alarm_Rooster_02.ogg

PHP Fatal error: 
Cannot 'break' 2 levels in /owncloud/apps/music/3rdparty/getID3/getid3/module.audio.ogg.php on line 511

PHP Fatal error: 
Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /owncloud/lib/private/Files/Filesystem.php:776

Stack trace:
#0 /owncloud/lib/private/Files/View.php(2034): OC\Files\Filesystem::normalizePath('/user...')
#1 /owncloud/lib/private/Files/View.php(1152): OC\Files\View->unlockFile('/user...', 1)
#2 [internal function]: OC\Files\View->OC\Files\{closure}()
#3 /owncloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))
#4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()
#5 /opteryx.org/owncloud/lib/private/Files/Stream/OC.php(123): fclose(Resource id #888)
#6 [internal function]: OC\Files\Stream\OC->stream_close()
#7 {main}
  thrown in /owncloud/lib/private/Files/Filesystem.php on line 776
```

**Comment by paulijar** [comment]
This is, again, the same issue as #557, #538, and #545. The issue is already fixed but the fix is not yet included in any release. You can fix the issue yourself by substituting "break 2;" with "break;" in /owncloud/apps/music/3rdparty/getID3/getid3/module.audio.ogg.php on line 511.
