### ISSUE TITLE
Reloading Nextcloud 13 sometimes fails on unhandled exception

### ISSUE THREAD

**Issue by paulijar** [owncloud/music#636]
Occasionally, reloading Nextcloud 13 fails and there's only a blue error screen showing an error message and stack trace. The trace shows that there has been an unhandled exception `OCP\Files\NotFoundException` in the *file updated* hook of the Music app. Reloading the page again solves the issue.

NC13 seems to be triggering the update hook when it creates some files on the page reload for its internal use (?). Maybe these files are sometimes short-living and no longer exist when the hook actually gets executed which could explain why we get the exception when trying to read information of the passed in file node.

This may be a design flaw in NC13, but regardless, the Music app should probably be prepared for such hook invocations. Adding a try-catch block around the file node access would probably be enough to solve this issue.

Here's an example of the error message (with Finnish localization):
```
Sisäinen palvelinvirhe
Palvelin ei kyennyt käsittelemään pyyntöäsi.

Jos tämä tapahtuu uudelleen, lähetä alla olevat tekniset tiedot palvelimen ylläpitäjälle.

Lisätietoja on palvelimen lokitiedostossa.

Tekniset tiedot
Etäosoite: *IP REMOVED*
Pyynnön tunniste: MyHbpjwvyb54UMSG6Vzt
Tyyppi: OCP\Files\NotFoundException
Koodi: 0
Viesti:
Tiedosto: /var/www/html/nextcloud/lib/private/Files/Node/Node.php
Rivi: 97

Jälki
#0 /var/www/html/nextcloud/lib/private/Files/Node/Node.php(336): OC\Files\Node\Node->getFileInfo()
#1 /var/www/html/nextcloud/apps/music/hooks/filehooks.php(49): OC\Files\Node\Node->getType()
#2 [internal function]: OCA\Music\Hooks\FileHooks::updated(Object(OC\Files\Node\File))
#3 /var/www/html/nextcloud/lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Array, Array)
#4 /var/www/html/nextcloud/lib/private/Hooks/PublicEmitter.php(36): OC\Hooks\BasicEmitter->emit('\\OC\\Files', 'postWrite', Array)
#5 /var/www/html/nextcloud/lib/private/Files/Node/Root.php(136): OC\Hooks\PublicEmitter->emit('\\OC\\Files', 'postWrite', Array)
#6 /var/www/html/nextcloud/lib/private/Files/Node/Node.php(108): OC\Files\Node\Root->emit('\\OC\\Files', 'postWrite', Array)
#7 /var/www/html/nextcloud/lib/private/Files/Node/File.php(66): OC\Files\Node\Node->sendHooks(Array)
#8 /var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php(95): OC\Files\Node\File->putContent('/**\n * @copyrig...')
#9 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(236): OC\Files\SimpleFS\SimpleFile->putContent('/**\n * @copyrig...')
#10 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(118): OC\Template\SCSSCacher->cache('/var/www/html/n...', '77985e06-server...', 'server.scss', Object(OC\Files\SimpleFS\SimpleFolder), '/nextcloud/core...')
#11 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(109): OC\Template\SCSSCacher->process('/var/www/html/n...', 'core/css/server...', 'core')
#12 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(61): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/var/www/html/n...', 'core/css/server...')
#13 /var/www/html/nextcloud/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/server')
#14 /var/www/html/nextcloud/lib/private/TemplateLayout.php(266): OC\Template\ResourceLocator->find(Array)
#15 /var/www/html/nextcloud/lib/private/TemplateLayout.php(182): OC\TemplateLayout::findStylesheetFiles(Array)
#16 /var/www/html/nextcloud/lib/private/legacy/template.php(207): OC\TemplateLayout->__construct('user', 'music')
#17 /var/www/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php(157): OC_Template->fetchPage()
#18 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(114): OCP\AppFramework\Http\TemplateResponse->render()
#19 /var/www/html/nextcloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Music\Controller\PageController), 'index')
#20 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('PageController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#21 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#22 /var/www/html/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#23 /var/www/html/nextcloud/lib/base.php(998): OC\Route\Router->match('/apps/music/')
#24 /var/www/html/nextcloud/index.php(37): OC::handleRequest()
#25 {main}
```

**Comment by paulijar** [comment]
The fix is published in v0.6.0.
