### ISSUE TITLE
Problem while running background job.

### ISSUE THREAD

**Issue by cdamken** [owncloud/music#668]
Owncloud version: 10.0.9
Ubuntu 16.0.4
music: 0.9.2

I saw this error in my log file:

```
{"reqId":"S7wEhM7edykyfitZ7VsX","level":3,"time":"2018-08-14T18:40:53+02:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message"
:"Error while running background job (class: OC\BackgroundJob\Legacy\RegularJob, arguments: Array
(
    [0] => OCA\Music\Backgroundjob\CleanUp

    [1] => run
)
): {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'DELETE FROM `oc_music_tracks` WHERE `id` IN (
				SELECT `id` FROM (
					SELECT `oc_music_tracks`.`id`
					FROM `oc_music_tracks` LEFT JOIN `oc_filecache`
					ON `oc_music_tracks`.`file_id` = `oc_filecache`.`fileid`
					WHERE `oc_filecache`.`fileid` IS NULL
				) mysqlhack
			)':

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","Code":0,"Trace":"
#0 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1015): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'DELETE FROM `oc...', Array)
#2 /var/www/owncloud/lib/private/DB/Connection.php(210): Doctrine\DBAL\Connection->executeUpdate('DELETE FROM `oc...', Array, Array)
#3 /var/www/owncloud/apps/music/db/maintenance.php(69): OC\DB\Connection->executeUpdate('DELETE FROM `oc...')
#4  /var/www/owncloud/apps/music/db/maintenance.php(80): OCA\Music\Db\Maintenance->removeUnreferencedDbRows('*PREFIX*music_t...', '*PREFIX*filecac...', 'file_id', 'fileid')
#5 /var/www/owncloud/apps/music/db/maintenance.php(128): OCA\Music\Db\Maintenance->removeObsoleteTracks()
#6 /var/www/owncloud/apps/music/backgroundjob/cleanup.php(28): OCA\Music\Db\Maintenance->cleanUp()
#7 [internal function]: OCA\Music\Backgroundjob\CleanUp::run()
#8 /var/www/owncloud/lib/private/BackgroundJob/Legacy/RegularJob.php(31): call_user_func(Array)
#9 /var/www/owncloud/lib/private/BackgroundJob/Job.php(57): OC\BackgroundJob\Legacy\RegularJob->run(Array)
#10 /var/www/owncloud/cron.php(121): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#11 {main}","File":"/var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","Line":115}"}
```

When I run the query in the DB:

``` 
MariaDB [ocdamken]> SELECT `oc_music_tracks`.`id` FROM `oc_music_tracks` LEFT JOIN `oc_filecache` ON `oc_music_tracks`.`file_id` = `oc_filecache`.`fileid` WHERE `oc_filecache`.`fileid` IS NULL;
Empty set (0.07 sec)
```

**Comment by paulijar** [comment]
Thanks for the report. Is this something which has happened only once, and usually the background job runs without problems? It should run once per 15 minutes and you can also run the cleanup job manually using the `occ` command `music:cleanup`.

Looking at the error message, the case has probably been such that one of the relevant database tables has been locked by another process when the cleanup task tried to modify it. Hence, the operation failed. If this happens only rarely, then we probably don't need to worry about it; the job is run again after 15 minutes and then it probably succeeds.

**Comment by paulijar** [comment]
With no further information, I assume this is a sporadic and non-critical issue, and can be safely ignored.
